/**
 * Activity Type Constants
 * 
 * Consistent action types following OBJECT_ACTION naming convention
 */

export const ActivityType = {
  // Task Actions
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  
  // Note Actions
  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_UPDATED: 'NOTE_UPDATED',
  NOTE_DELETED: 'NOTE_DELETED',
  
  // Doc Actions
  DOC_CREATED: 'DOC_CREATED',
  DOC_UPDATED: 'DOC_UPDATED',
  DOC_DELETED: 'DOC_DELETED',
  
  // Event Actions
  EVENT_SCHEDULED: 'EVENT_SCHEDULED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_DELETED: 'EVENT_DELETED',
  
  // Lead Actions
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_UPDATED: 'LEAD_UPDATED',
  LEAD_CONVERTED: 'LEAD_CONVERTED',
  LEAD_STATUS_CHANGED: 'LEAD_STATUS_CHANGED',
  LEAD_DELETED: 'LEAD_DELETED',
  
  // Opportunity Actions
  OPPORTUNITY_CREATED: 'OPPORTUNITY_CREATED',
  OPPORTUNITY_UPDATED: 'OPPORTUNITY_UPDATED',
  OPPORTUNITY_STAGE_CHANGED: 'OPPORTUNITY_STAGE_CHANGED',
  OPPORTUNITY_WON: 'OPPORTUNITY_WON',
  OPPORTUNITY_LOST: 'OPPORTUNITY_LOST',
  OPPORTUNITY_DELETED: 'OPPORTUNITY_DELETED',
  
  // Contact Actions
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  
  // Client Actions
  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_UPDATED: 'CLIENT_UPDATED',
  CLIENT_DELETED: 'CLIENT_DELETED',
  
  // Generic Actions
  ASSIGNED: 'ASSIGNED',
  OWNER_CHANGED: 'OWNER_CHANGED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  COMMENT_ADDED: 'COMMENT_ADDED',
} as const;

export type ActivityTypeValue = typeof ActivityType[keyof typeof ActivityType];
